# Generated by Django 2.2 on 2020-09-13 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200913_0423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='profile',
            name='about_user',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='profile',
            name='git_profile',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Профиль на GitHub'),
        ),
    ]
