# Generated by Django 2.2 on 2020-08-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200810_1306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='type',
            new_name='types',
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Тип'),
        ),
    ]
